[package]
name = "glkcli-rust"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "glkcli"
path = "src/main.rs"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
anyhow = "1.0"
thiserror = "1.0"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
